import { Inter } from "next/font/google";
import { AppProvider } from "../context/AppContext";
import Navbar from "./components/Navbar";
import "./globals.css";
import FooterComponent from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AppProvider>
					<Navbar />
					{children}
					<FooterComponent />
				</AppProvider>
			</body>
		</html>
	);
}
